// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/feeds/[seriesId].ts";
import * as $1 from "./routes/api/feeds/[seriesId]/[episodeId]/chapters.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/CopyButton.tsx";

const manifest = {
  routes: {
    "./routes/api/feeds/[seriesId].ts": $0,
    "./routes/api/feeds/[seriesId]/[episodeId]/chapters.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/CopyButton.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
